### ISSUE TITLE
Conversation Flow Chart for Chapter 1

### ISSUE THREAD

**Issue by mllemango** [de-souza-capstone-2020/Celestial-Bodies#9]
#### Mandatory Description
As a patient
I want converse with the chatbot
so that I can learn from a "natural" conversation

#### Additional Description of User Story
Flow chart of chapter 1

#### Acceptance Criteria
PNG of flowchart

#### Checklist (Optional)
- [ ] Determine flow chart software (?)
- [ ] Map out the conversation
- [ ] Review with client

**Comment by itsDZhang** [comment]
Excel Document
